version: "3.8"

services:
  
  orthanc:
    image: osimis/orthanc:24.1.0-full-meddream
    build: orthanc
    restart: unless-stopped
    ports: ["8042:8042"]
    volumes: ["orthanc-storage:/var/lib/orthanc/db"]
    environment:
      VERBOSE_STARTUP: "true"
      ORTHANC__REGISTERED_USERS: |
        {
          "demo": "demo",
          "meddream": "R4Y8p7cG5cbos6"
        }
      OE2_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_MED_DREAM_VIEWER: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__MED_DREAM_VIEWER_PUBLIC_ROOT: "http://localhost:8080/"

  meddream:
    image: meddream/orthanc-dicom-viewer:8.3.1
    restart: unless-stopped
    user: root
    ports: ["8080:8080"]
    depends_on:
      - orthanc
    environment:
      integration: "study"
    volumes:
      - ./meddream/application.properties:/opt/meddream/application.properties
      - ./meddream/system.json:/opt/meddream/sys/system.json
      - ./meddream/license:/opt/meddream/license

volumes:
  orthanc-storage:
    driver: local
    driver_opts:
      type: none
      device: /tmp/orthanc
      o: bind
